/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "Headers/Macros.h"
#include "Headers/communications.h"
#include "Headers/delay_functions.h"
#include <stddef.h>
#include <string.h>

// Define el comando AT
const char* command_init = "AT\r\n";
uint8_t button_pressed = 0;



int main(void)
{

	char response[100];
    // Inicializar la UART
    uart_init();
    delay_ms(50);
    comunicate_process();
    delay_ms(50);

    while(1) {
            // Detectar flanco de subida (botón presionado)
            if((GPIOx_IDR(GPIOB_BASE) & (1U << 1)) && !button_pressed) {
                button_pressed = 1;  // Marcar que el botón fue presionado

                delay_ms(50); // Pequeño debounce
                comunicate_process();
                transmit_string(command_init);
                delay_ms(50);

                receive_string(response, sizeof(response));

                if (strcmp(response, "OK") == 0 || strcmp(response, "OK\r\n") == 0) {
                    recive_data_ok();  // Indica que la comunicación fue exitosa
                } else {
                    recive_data_error();  // Indica error
                }
            }

            // Detectar flanco de bajada (botón liberado)
            if(!(GPIOx_IDR(GPIOB_BASE) & (1U << 1))) {
                button_pressed = 0;  // Permitir nueva detección
        }
    }
}

