/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "Headers/Macros.h"
#include "Headers/communications.h"
#include "Headers/delay_functions.h"
#include <stddef.h>
#include <string.h>

// Define el comando AT
const char* command_init = "AT\r\n";
const char* set_name = "AT+NAMEMyFirstTest\r\n";
const char* set_pin= "AT+PIN4321\r\n";

uint8_t button_pressed = 0;



int main(void)
{
	//Clock enable bus RCC USART and GPIO
	RCC_APB1ENR |= (1U << 18);
	RCC_APB2ENR |= (0x3U << 3);
	//Global-interrupt enable
	//__asm("CPSIE I");  // Habilitar interrupciones globales (setea el bit I del xPSR)
	    //__asm volatile ("cpsie i");

    // Inicializar la UART
	init_system();
	delay_ms(50);
	comunicate_process();
	delay_ms(50);
    uart_init();
    button_enable();


    while(1) {

            // Detectar flanco de subida (botón presionado)
            if((GPIOx_IDR(GPIOB_BASE) & (1U << 1)) && !button_pressed) {
                button_pressed = 1;  // Marcar que el botón fue presionado

                delay_ms(50); // Pequeño debounce
                //transmit_string(set_name);
                recive_data_ok();
                delay_ms(50);
                //elay_ms(50); // Pequeño debounce
                //transmit_string(set_pin);
                recive_data_ok();
                delay_ms(50);


            }

            // Detectar flanco de bajada (botón liberado)
            if(!(GPIOx_IDR(GPIOB_BASE) & (1U << 1))) {
                button_pressed = 0;  // Permitir nueva detección
        }

    }
}

